version: '3.8'

services:
  db:
    image: postgres:15
    container_name: 6ticket_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sucesso
      POSTGRES_DB: sixtech
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: